title: Blah Blah Blah
author: GitHub Blah
email: your-email@Blah.com
description: > # this means to ignore newlines until "baseurl:"
Blah Blah Blah. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_Blah: your-twitter-handle
github_Blah:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
